spring:
  application:
    name: delivery
  config:
    import:
      - configserver:http://localhost:9000

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    password: password
    username: admin
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8050



