spring:
  application:
    name: stock
  config:
    import:
      - configserver:http://config:9000
  cloud:
    config:
      profile: docker
  datasource:
    username: admin
    password: password
    url: jdbc:postgresql://postgres:5432/stock
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate




